### PR TITLE
Add network selector option

### PR DESCRIPTION
**Pull request by chromatic**
Note that not all networks support segwit, so for those networks which don't, create only compat addresses instead.

### CODE REVIEW

**Comment by bbrtj** [comment]
That's a good idea, thank you. The only thing which I find odd is the number of addresses generated when there is no segwit support. I'd expect the number to be set to `$compat_addresses + $segwit_addresses`, not just the latter. This way we would get the same number of addresses for every network and the `-c` option won't be ignored for some of them.

Also, this seems to be incorrect: `the script will fall back to generating only compat addresses`. Technically speaking, there are no segwit compat addresses if the network does not support segwit. These are legacy addresses (though they aren't really legacy if the network does not support segwit, but that's how they are called in Bitcoin::Crypto).

I also think there's no harm in pulling Test::Exception from CPAN instead of using `eval` to test. But you can skip that one, as I switched Bitcoin::Crypto to Test2 lately and may do the same with PaperWallet. Test2::V0 has some exception-testing routines built in, so that will be taken care of.

**Comment by chromatic** [comment]
Thanks for the review comments. I've pushed two more commits to address your concerns. I'm happy to squash everything into a single commit if you prefer, after you've reviewed that both new commits are sensible.

**Review by bbrtj — APPROVED** [review]
It's fine now, thank you :)

**Comment by bbrtj** [comment]
Released in 1.13

**Pull request merged**
